### ISSUE TITLE
Cart is still filled after completed checkout

### ISSUE THREAD

**Issue by jensolafkoch** [statamic-rad-pack/shopify#139]
When a checkout is completed on the Shopify side (paid and Thank-you-page shown), and I go back (in the same session) our cart is still filled with the items just bought.

Is this the expected behaviour? Shouldn't the cart be emptied after a completed checkout?

**Comment by jensolafkoch** [comment]
Any news on this one?

**Comment by jackabox** [comment]
@jensolafkoch This was should have been updated a while back, but would have required an update to your code. Are you using the latest checkout.js? https://github.com/jackabox/statamic-shopify/blob/main/resources/js/shopify/checkout.js

**Comment by jensolafkoch** [comment]
Thanks, I missed that one, sorry. Will check it out.
