### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by freshface** [statamic-rad-pack/shopify#140]
In site.js i am loading the javascript:

```
import checkout from './vendor/shopify/checkout'
import cart, { setCartCount } from './vendor/shopify/cart'
import productForm from './vendor/shopify/products'

new checkout()
new setCartCount()
new productForm()
new cart()

```

But got an error: **is not a constructor** in checkout.js

<img width="1272" alt="Screenshot 2022-11-04 at 11 49 27" src="https://user-images.githubusercontent.com/103913/199955277-9bb453e5-0865-410b-a899-16ec2ca1f77a.png">

**Comment by ryanmitchell** [comment]
Yeah its the `new` causing the issue:

```
checkout()
setCartCount()
productForm()
cart()
```

They are functions not classes.
