### ISSUE TITLE
Statamic 4 Installation Issues

### ISSUE THREAD

**Issue by KieMaverick** [statamic-rad-pack/shopify#145]
Hello, I'm having a few issues trying to install into Statamic 4.0

I'm not entirely sure where the conflict lies between Statamic 4.0 & Peak Starter Kit. 

This is an entirely clean install, and the error comes directly after requiring the statamic-shopify package. 

I'm inclined to believe this is an incompatibility with Statamic 4.0

` @php artisan statamic:install --ansi

   UnexpectedValueException 

  Invalid route action: [Webhooks\OrderCreateController].

  at vendor/laravel/framework/src/Illuminate/Routing/RouteAction.php:92
     88▕      */
     89▕     protected static function makeInvokable($action)
     90▕     {
     91▕         if (! method_exists($action, '__invoke')) {
  ➜  92▕             throw new UnexpectedValueException("Invalid route action: [{$action}].");
     93▕         }
     94▕ 
     95▕         return $action.'@__invoke';
     96▕     }

  i   `Webhooks\OrderCreateController` was not found: Controller class `Webhooks\OrderCreateController` for one of your routes was not found. Are you sure this controller exists and is imported correctly? `

Any Insight would be helpful.

**Comment by KieMaverick** [comment]
After doing some more digging, I can see this is an incompatibility with the newest version of Laravel 

The following pull request appears to address the issues - https://github.com/jackabox/statamic-shopify/pull/144

**Comment by jackabox** [comment]
Thanks for this - I will look to get this rectified as soon as possible.

**Comment by edwwaarrdd** [comment]
To get the import working in the control panel I also had to remove the findBySlug method from the ImportCollectionsForProductJob class. 
See #146

**Comment by mnlmaier** [comment]
@jackabox do you have any eta for official v4 compatibility? :)

**Comment by edalzell** [comment]
> @jackabox do you have any eta for official v4 compatibility? :)

We're working on bringing this addon into the Rad Pack (2nd party addons with Statamic support), so please stand by.
