### ISSUE TITLE
Uncaught (in promise) Error: [{"message":"Field 'presentmentPrices' doesn't exist on type 'ProductVariant'

### ISSUE THREAD

**Issue by klickreflex** [statamic-rad-pack/shopify#147]
My cart stopped working  entirely recently (last purchase happened on June 27ths.

I'm getting the following error everywhere. I already tried:
-  Updating from 1.7.2 to 1.7.8 (including publishing assets again, testing with and without my customizations)
-  Wipe and reimport all Products and Variants

Any ideas what could cause this?

```
index.js:3972 Uncaught (in promise) Error: [{"message":"Field 'presentmentPrices' doesn't exist on type 'ProductVariant'","locations":[{"line":1,"column":94}],"path":["fragment VariantFragment","presentmentPrices"],"extensions":{"code":"undefinedField","typeName":"ProductVariant","fieldName":"presentmentPrices"}},{"message":"Field 'description' doesn't exist on type 'ScriptDiscountApplication'","locations":[{"line":1,"column":904}],"path":["fragment DiscountApplicationFragment","... on ScriptDiscountApplication","description"],"extensions":{"code":"undefinedField","typeName":"ScriptDiscountApplication","fieldName":"description"}}]
```

@jackabox Your demo shop has the same issue:
https://shopify.jackwhiting.dev/

**Comment by klickreflex** [comment]
Yes:
![CleanShot 2023-07-25 at 16 17 09@2x](https://github.com/jackabox/statamic-shopify/assets/435825/e5428606-6c3f-484e-babf-1b974e78f075)

The error goes away if I stop trying to update `shopifyCheckout` in initNewCheckout
 
<img width="590" alt="CleanShot 2023-07-25 at 16 17 42@2x" src="https://github.com/jackabox/statamic-shopify/assets/435825/fd370822-3353-4d06-8f85-eb60a1d30a74">


But this has the side effect of "forgetting" the entire Cart with every page reload.

**Comment by jackabox** [comment]
Might be worth trying the following:

```
const initNewCheckout = async () => {
  checkout = await client.checkout.create()
  localStorage.setItem('statamic.shopify.cart.id', checkout.id)
  return checkout.id
}
```

Then wherever `initiNewCheckout` is called, can you change the line from `initiNewCheckout()` to `let shopifyCheckout = initiNewCheckout()`

**Comment by klickreflex** [comment]
I tried it, but unfortunately this also makes the Cart lose everything on reload.

**Comment by klickreflex** [comment]
Can you confirm that your Demo site has the same issue once you update `shopify-buy` to a current version? (I tried everything from 2.12 through 2.20)

**Comment by klickreflex** [comment]
I guess something is wrong too when initNewCheckout runs twice, isn't it?

<img width="364" alt="CleanShot 2023-07-25 at 17 13 28@2x" src="https://github.com/jackabox/statamic-shopify/assets/435825/8ce089b8-6c6c-419b-bf8d-73c12bfbb9ed">

**Comment by klickreflex** [comment]
If I remove `initNewCheckout()` in the else branch of `(if (! shopifyCheckout) {`, the cart stops forgetting its contents all the time, not sure if it has any undesired side effects though:

![CleanShot 2023-07-25 at 17 39 32@2x](https://github.com/jackabox/statamic-shopify/assets/435825/cf89806f-e497-4e76-bee2-f368f8602a24)

**Comment by klickreflex** [comment]
Another change I needed to make for the updated Shopify-Buy Button:
Prices in the Cart table were showing `NaN`. The actual numbers are now nested under a `amount` key (so `variant.price` becomes `variant.price.amount`):

<img width="578" alt="CleanShot 2023-07-25 at 17 56 21@2x" src="https://github.com/jackabox/statamic-shopify/assets/435825/a70afabd-8005-4719-b171-6d0bb6f0d1f4">

**Comment by ryandc** [comment]
Can confirm the demo isn't adding items to the cart, and the cart itself isn't loading.

**Comment by jensolafkoch** [comment]
@klickreflex

Have you been able to solve that problem? I've ran into something which looks a bit similar, and I wonder if something changed on the Shopify side of things back then in July ...

**Comment by klickreflex** [comment]
The stuff I described above is all I did and it has been working since.

**Comment by jensolafkoch** [comment]
@klickreflex Thanks! :-)
