### ISSUE TITLE
Transfer & Update

### ISSUE THREAD

**Issue by edalzell** [statamic-rad-pack/shopify#148]
- [x] get access to the repo so we can transfer
- [x] update namespace
- [x] merge https://github.com/jackabox/statamic-shopify/pull/144
- [x] add test coverage
- [x] release new version
- [x] add to packagist
- [x] add Stripe account to Statamic Marketplace account
- [x] update Marketplace
- [x] new demo store link
- [x] new docs link

This brings it in-house while making it compatible with latest Statamic & Laravel.

**Comment by ryanmitchell** [comment]
Also need to remove "Sponsor this project" in the right hand side bar

**Comment by edalzell** [comment]
> Also need to remove "Sponsor this project" in the right hand side bar

Why?

**Comment by ryanmitchell** [comment]
Currently sponsoring Jack whiting?

**Comment by edalzell** [comment]
> Currently sponsoring Jack whiting?

We could change that to the Rad Pack
