### ISSUE TITLE
Tailwind Classes Not Working

### ISSUE THREAD

**Issue by breyell** [statamic-rad-pack/shopify#196]
I see some `*-grey-30` classes and guessing they're supposed to be `*-gray-300`? I see a `bg-grey-30` and `border-grey-30` but there could be others. Noticed this when clicking on a variant which opens a modal. The "Edit Variant" text also appears twice.

<img width="1392" alt="Screenshot 2024-01-11 at 7 42 31 PM" src="https://github.com/statamic-rad-pack/shopify/assets/4373031/db2285d8-dfa3-402f-abb9-d4e85f310625">

**Comment by ryanmitchell** [comment]
Yeah that styling isnt good - some things must have changed in core that we need to update to. Leave it with me!
