### ISSUE TITLE
 Argument #4 ($hostName) must be of type string, null given

### ISSUE THREAD

**Issue by freshface** [statamic-rad-pack/shopify#198]
Hi

I am installing this plugin and composer throws this error: https://flareapp.io/share/Vme9Adnm
Any ideas?

**Comment by ryanmitchell** [comment]
It seems like you havent defined the config('shopify.url') value. We have it looking for `SHOPIFY_APP_URL` in the .env if you want to define it there.

**Comment by freshface** [comment]
Hi Ryan, indeed.
Wasn't that clear in the installation guide :)
