### ISSUE TITLE
Checkout Confirmation Continue Shopping

### ISSUE THREAD

**Issue by adnankussair** [statamic-rad-pack/shopify#202]
Upon checkout confirmation there seems to be a continue shopping button that Shopify's hosted checkout displays. This button poses a bit of a user experience issue because it takes you to the default Shopify store channel homepage which obviously doesn't exist since we are using statamic for the "brochure" side of things. 

Are you aware of a way to address this? I think only the highest plan with Shopify allows modification of the checkout templates in Shopify.

![image](https://github.com/statamic-rad-pack/shopify/assets/239259/86a77a48-2896-4c24-91a7-54720771f9b2)

![image](https://github.com/statamic-rad-pack/shopify/assets/239259/cf44d6cc-26ce-4c34-b9be-83496bc8607d)

**Comment by ryanmitchell** [comment]
You can remove the link by entering a blank value here:
![CleanShot 2024-02-06 at 07 47 14@2x](https://github.com/statamic-rad-pack/shopify/assets/51899/6babc4a8-4356-41d2-840a-e1a7ae2c8be9)

Instructions here - https://meetanshi.com/blog/remove-return-to-cart-from-shopify-checkout-page/

just search for "Return to store link label"

**Comment by ryanmitchell** [comment]
I think you would be best directing these questions to shopify - it’s not really in the remit of this add on.

**Comment by adnankussair** [comment]
@ryanmitchell I appreciate the help this far. I did reach out to Shopify support prior to posting here and they had no clue how to address these other than stating "sign up" for a paid plan and all the issues will be resolved, which  I know that is not accurate. I was just trying to see how you addressed these with your add-on in situations where the site is infact live with customers flowing through.

**Comment by ryanmitchell** [comment]
We have a couple of development projects using the add on at the moment. If/when we solve it I’ll update here.

**Comment by adnankussair** [comment]
Thanks @ryanmitchell I appreciate your help on this. 🙏🏽

**Comment by adnankussair** [comment]
@ryanmitchell The solution presented in the link doesn't make the continue shopping button disappear:

<img width="1269" alt="Screenshot 2024-02-06 at 7 33 33 AM" src="https://github.com/statamic-rad-pack/shopify/assets/239259/01df59b9-aed7-418c-9038-e77747484b36">

This matters in the context of this addon because it's a bit of a "hacky" user flow. Seems like Shopify is assuming every checkout session has a store. This won't be an issue if the Continue shopping button destination is either configurable or we can remove it altogether. If Shopify allowed using custom CSS in the checkout screens, we could just set the button to `display: none`, but Shopify does not.

Ultimately, I think how to address this and have Shopify set up to pair perfectly with this addon should be included in the documentation.

Two issues need to be resolved in order of importance:

1. The continue shopping button should be able to be removed or it's destination customized
2. The root of the shopify hosted domain should take the user to the homepage of the statamic site not to the online store channel (as technically an online store channel doesn't exist).

**Comment by ryanmitchell** [comment]
As stated, I'll update here if/when I find a resolution, but as far as I'm concerned this a Shopify issue not an add-on one.

**Comment by ryanmitchell** [comment]
Our solution to this is to add a JS location redirect in the shopify theme. It works fine.

**Comment by adnankussair** [comment]
> Our solution to this is to add a JS location redirect in the shopify theme. It works fine.

Yup. I ended up doing exactly the same.
