### ISSUE TITLE
Make Shopify fields read only

### ISSUE THREAD

**Issue by JonKaric** [statamic-rad-pack/shopify#203]
### Description

Currently, it's possible to change data in the Statamic CP for fields whos data comes from Shopify. This can be confusing for developers and store owners alike who aren't sure where they should be amending product data. 

It can also cause conficts if product data is changed on Statamic, as the API and checkout would both be showing a different price than what was advertised.

I think it's best to have **data** come from Shopify, and **content** from Statamic. 

**Products**
- Title
- Content
- Options
- Gallery
- Vendor
- Product Type
- Product Tags
- Product Collections

The same goes for any fields inside of the following taxonomies & collections whos data comes from Shopify. It would be best to disable the creation of these too. 
- Products
- Variants (This already does a good job of making fields readonly)
- Product Collections
- Product Tags
- Product Type
- Product Vendor

### Steps to reproduce

N/A

### Environment

N/A

**Comment by ryanmitchell** [comment]
See https://github.com/statamic-rad-pack/shopify/pull/204
