### ISSUE TITLE
Storefront API Client missing from service provider

### ISSUE THREAD

**Issue by ryanhissey** [statamic-rad-pack/shopify#209]
### Description

When trying to use `$client = app(Shopify\Clients\Storefront::class);`

You get the error:

`Unresolvable dependency resolving [Parameter #0 [ <required> string $domain ]] in class Shopify\Clients\Graphql`

We are missing it in the service provider

### Steps to reproduce

try to use `$client = app(Shopify\Clients\Storefront::class);`

### Environment

Application Name: Statamic
Laravel Version: 10.44.0
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.4.9

Statamic
Addons: 3
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.49.0 PRO

**Comment by ryanmitchell** [comment]
This addon doesn’t connect to the storefront through PHP so we have no reason to bind it. 

If you need it in your own code you should add it in your service provider.

**Comment by ryanhissey** [comment]
Apologies, Will add it in my own code. Thanks for taking a look anyways 🙌
