### ISSUE TITLE
Exception on Windows machine during initializing of FileSessionStorage('/tmp/php_sessions')

### ISSUE THREAD

**Issue by jensolafkoch** [statamic-rad-pack/shopify#220]
### Description

On Windows 11, development with Laragon, same with Herd:

After I've updated an existing installation from Statamic 3.4, Laravel 8 and addon version 1.6 to latest/current versions, I got the following error (here the output from composer) :

```
 ErrorException

  mkdir(): No such file or directory

  at vendor\shopify\shopify-api\src\Auth\FileSessionStorage.php:22
     18▕      */
     19▕     public function __construct(string $path = '/tmp/shopify_api_sessions')
     20▕     {
     21▕         if (!is_dir($path)) {
  ➜  22▕             mkdir($path);
     23▕         }
     24▕
     25▕         $this->path = $path;
     26▕     }

  1   vendor\shopify\shopify-api\src\Auth\FileSessionStorage.php:22

  2   vendor\statamic-rad-pack\shopify\src\ServiceProvider.php:163
      Shopify\Auth\FileSessionStorage::__construct("/tmp/php_sessions")
```

I changed the code in vendor\statamic-rad-pack\shopify\src\ServiceProvider.php:163 from

```
        Context::initialize(
            apiKey: $key,
            apiSecretKey: config('shopify.auth_password'),
            scopes: ['read_metaobjects', 'read_products'],
            hostName: config('shopify.url'),
            //sessionStorage: new FileSessionStorage('/tmp/php_sessions'),
            // Windows:
            sessionStorage: new FileSessionStorage(env('SHOPIFY_SESSION_PATH', getenv('TEMP') . '/shopify_api_sessions')),
            apiVersion: config('shopify.api_version') ?? '2023-07',
            isEmbeddedApp: false,
            isPrivateApp: config('shopify.api_private_app') ?? false,
        );

```

- and it does work again, at least I get no exceptions and the app launches in the browser.

I must admit that I don't understand _why_ this change is working. I hope someone do and can solve the problem?

Many thanks!

### Steps to reproduce

See above.

### Environment

Environment
Application Name: permanent
Laravel Version: 11.8.0
PHP Version: 8.3.3
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: kb-permanent.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.5.0 PRO

Statamic Addons
plugrbase/statamic-maintenance-mode: 1.07
statamic-rad-pack/shopify: 3.3.1

**Comment by ryanmitchell** [comment]
I've opened a PR here with the changes and a bit of an explanation: https://github.com/statamic-rad-pack/shopify/pull/221

**Comment by jensolafkoch** [comment]
@ryanmitchell 

Many thanks! :-)
