### ISSUE TITLE
Variants are PUBLISHED when product is DRAFT

### ISSUE THREAD

**Issue by dgrigg** [statamic-rad-pack/shopify#242]
### Description

The problem is related to archived products in Shopify. The archived products in shopify, when imported to statamic, are set to draft, which works great. The problem comes with the variants. The variants of those products are still published and not draft like the parent product.

We would need to slightly tweak the import process to set to draft (in statamic) the variants of archived products.

### Steps to reproduce

1. Import products from Shopify that have variants
2. Archive the product in Shopify 
3. The variants stay published in Statamic even though the parent product goes to Draft

### Environment

Environment
Application Name: Statamic
Laravel Version: 10.48.22
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: localhost:3000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.25.0 PRO

Statamic Addons
aerni/advanced-seo: 2.9.0
pxlp/headless: dev-main
statamic-rad-pack/shopify: 4.0.3

**Comment by ryanmitchell** [comment]
I don't agree. 

Variants are relationship data and so should be always published, they shouldn't be linked to the product's publish state, especially as product publish status can now be scheduled.

You access variants through products so getting the product publish status should be trivial.

**Comment by dgrigg** [comment]
By leaving variants in an always published state they are in conflict with the actual state of the Shopify system which causes at least two issues:

1. For the site visitor, content is available for viewing and use that from the Shopify world would not be the case. A product manager may have archived a product in Shopify to prevent customers from accessing an product that is no longer carried. On the website those variants, by staying published, present information that it not accurate.  If they went to a Draft state when the product was archived that situation can be prevented. 

2. For the CMS editor, leaving variants always published makes it very difficult to easily link to actual 'live' products/variants. Take the example of a piece of content that shows data from a featured Shopify variant with a link to buy. When the CMS editor is looking at the list in Statamic of variants to select one, they have no easy way to filter the actual 'live' vs 'archived' variants as all the variants appear to be live.

At the very least a config option to keep the variants in sync with the parent product's Shopify status would be extremely helpful.

**Comment by ryanmitchell** [comment]
> By leaving variants in an always published state they are in conflict with the actual state of the Shopify system which causes at least two issues:
> 
> For the site visitor, content is available for viewing and use that from the Shopify world would not be the case. A product manager may have archived a product in Shopify to prevent customers from accessing an product that is no longer carried. On the website those variants, by staying published, present information that it not accurate. If they went to a Draft state when the product was archived that situation can be prevented.

But again you only get to variants through products, so this is incorrect. You aren't getting to variants directly (or shouldn't be).

> For the CMS editor, leaving variants always published makes it very difficult to easily link to actual 'live' products/variants. Take the example of a piece of content that shows data from a featured Shopify variant with a link to buy. When the CMS editor is looking at the list in Statamic of variants to select one, they have no easy way to filter the actual 'live' vs 'archived' variants as all the variants appear to be live.
> 
> At the very least a config option to keep the variants in sync with the parent product's Shopify status would be extremely helpful.

Im open to reviewing a PR on this but to be honest I think it's the wrong direction to take. The system is set up around linking to products, not variants.

**Comment by dgrigg** [comment]
In the CMS it's possible to select a variant directly for a relationship which leads to this exact scenario.

**Comment by ryanmitchell** [comment]
> In the CMS it's possible to select a variant directly for a relationship which leads to this exact scenario.

In the sense that all collections are yes, but you have the option as a developer of not allowing it.

**Comment by ryanmitchell** [comment]
For context, here is an example why I'm against the idea:

Product 1 gets added with a variant A and variant B
Client through the CP makes variant B unpublished
Product 1 gets re-saved in Shopify - what do we do - Shopify thinks variant B is published, but Statamic doesn't. Do we overwrite the status?

We are introducing ambiguity that doesn't need to be there - it's not an option in Shopify so shouldn't be in the sync. If I could turn off the publish field on variants in Statamic I would do that.

Ideally something will change in core around this idea - https://github.com/statamic/ideas/issues/743 - which would let us make the status be inherited from the product status.

**Comment by dgrigg** [comment]
Yes, its a 50/50 argument. Should the variant's published status be manually changed in Statamic when it's just a reflection of the  Shopify data, likely not?

**Comment by ryanmitchell** [comment]
Given the goal is to mirror Shopify's data I would say it should be overwritten. Regardless I think we're discussing something that can be worked around simply by not allowing the selection of variants in the CP by the developer.

**Comment by ryanmitchell** [comment]
Going to close this off. If you want to see the functionality, feel free to open a PR with the changes.
