### ISSUE TITLE
SHOPIFY_STOREFRONT_URL is ignored?

### ISSUE THREAD

**Issue by sunscreem** [statamic-rad-pack/shopify#251]
### Description

I've added a `SHOPIFY_STOREFRONT_URL` to my .env but it seems it being ignored on the cart page (continue to checkout button).

Looking at cart.js it seems to pull the url from the shopify API to use, and I can't seem to find any way in shopify to change it. Maybe someone knows how?

In the meantime I've fudged it:

```js

 // Replace the checkout URL
webUrl = webUrl.replace('shopify-domain', 'custom-checkout-domain')

 // Show Elements
showCartOverview(lineItems, subtotalPriceV2, webUrl)
```

### Steps to reproduce

n/a

### Environment

n/a

**Comment by ryanmitchell** [comment]
The url is returned by shopify so we can’t control it. Sorry.
