### ISSUE TITLE
Product status change on Shopify isn't showing in Statamic until the stache is cleared.

### ISSUE THREAD

**Issue by sunscreem** [statamic-rad-pack/shopify#252]
### Description

We've noticed that although most product changes at Shopify, such as a name or description change, are updated via the webhooks almost instantly, this doesn't appear to be the case for the published status. 

Is this a Statamic issue? 

### Steps to reproduce

1. Change a product status from published to draft
2. Webhook fires correct - product.yaml show the change
3. Product published remains unchanged until the Statche is cleared.

### Environment

Environment
Application Name: X
Laravel Version: 11.30.0
PHP Version: 8.2.25
Composer Version: 2.3.2
Environment: production
Debug Mode: OFF
URL: X
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en_GB

Cache
Config: CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single, bugsnag
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 7
Sites: 1
Stache Watcher: Disabled
Static Caching: half
Version: 5.36.0 PRO

Statamic Addons
statamic-rad-pack/shopify: 4.0.6

**Comment by ryanmitchell** [comment]
Is this a future dated product?

**Comment by sunscreem** [comment]
Hey @ryanmitchell I don't think we use dates at all on this project - but let me check.

**Comment by sunscreem** [comment]
Hey @ryanmitchell Double checked and no dates are used. I can email you over a quick video to show the issue if you would like?

**Comment by ryanmitchell** [comment]
On fresh installs your collection should be dated and publish dates are considered. I’m wondering if the line below needs to be GTE not GT :

https://github.com/statamic-rad-pack/shopify/blob/695be9f1267b32a498ee3f1509ddf2328758e9a8/src/Jobs/ImportSingleProductJob.php#L222

**Comment by sunscreem** [comment]
@ryanmitchell Thanks - I've tried disabling dates on the product collections and still seeing the same issue. Note that the published status in the control panel also shows the incorrect status until I clear the stache.

**Comment by ryanmitchell** [comment]
If you just resave the product rather than clearing the stache does it resolve it?

**Comment by sunscreem** [comment]
Thanks Ryan. If I save from the control panel it will overwrite the data on the product so here's how I saved it in tinker. You will see I clear the stache and everything is working as expected:

![image](https://github.com/user-attachments/assets/c1904b8d-6df1-40cf-ac17-22d036fc8e9c)

**Comment by ryanmitchell** [comment]
Weird. 

If you dd or log here <https://github.com/statamic-rad-pack/shopify/blob/695be9f1267b32a498ee3f1509ddf2328758e9a8/src/Jobs/ImportSingleProductJob.php#L227> what status is being set? I wonder if we also need to set `$entry->set('published', $published)` but I didnt think that was needed.

**Comment by sunscreem** [comment]
@ryanmitchell After a bunch of experimenting it does seem that with the `STATAMIC_STACHE_WATCHER` set to `false` that data changes on the products trigger an update to the stache, but the published status change doesn't. I'm not sure why. 

To work around it I've tried adding:

```php
Stache::store('entries::products')->clear();
Stache::store('entries::products')->warm();
```

Just [here](https://github.com/statamic-rad-pack/shopify/blob/695be9f1267b32a498ee3f1509ddf2328758e9a8/src/Jobs/ImportSingleProductJob.php#L239).

What are your thoughts on using that as a workaround? I'm tempted to raise this as a bug on the Statamic repo as I can't find any discussion of it anywhere and which is odd.

**Comment by ryanmitchell** [comment]
That shouldn’t be necessary. Saving the item should be enough. Did you try setting published in the data like I suggested?

**Comment by sunscreem** [comment]
I did yes - it didn't change anything - sorry I should have said earlier.

**Comment by ryanmitchell** [comment]
The whole thing seems odd - definitely not something we're seeing on our installs.
Are you running a queue?

**Comment by sunscreem** [comment]
No locally in testing no. I can try to recreate on a clean install that that helps?

**Comment by ryanmitchell** [comment]
You could listen for the ProductCreate/Delete/Update events and call the stache:clear in there.

**Comment by sunscreem** [comment]
Yeah - that's a plan. Tempted to try to recreate on a clean install anyway. Can you leave this open for now, I'll do that tomorrow if I get chance?

**Comment by sunscreem** [comment]
Hey @ryanmitchell I'm finally getting the bottom of this.

https://github.com/statamic-rad-pack/shopify/blob/2ff75c2b1f0fbe84f7283ba877078b6d114b7d32/src/Jobs/ImportSingleProductJob.php#L200-L232

Would you mind explaining what this code is doing?

**Comment by ryanmitchell** [comment]
It’s syncs the publication status and dates from shopifys online store channel

**Comment by sunscreem** [comment]
Cool thanks. Does that work with the publish status set in the $data array above?

I'm finding if I put a quickly addin  `$entry->published(true)` - or `$entry->published(false)` just before the `$entry-save()` on 238 it fixing my stache issue.

**Comment by ryanmitchell** [comment]
If you have an ‘online store’ channel in shopify - make sure you have the product available on it.

**Comment by sunscreem** [comment]
@ryanmitchell I've got some news on this one. I finally found the issue. 

I've made a video where I talk you through it. 5 mins long, but hopefully shows you what I'm seeing. 

Can upload to youtube and email you a link if thats okay?

**Comment by ryanmitchell** [comment]
Sure. Send me a DM on discord?
