### ISSUE TITLE
ErrorException Undefined variable $qty in ImportSingleProductJob

### ISSUE THREAD

**Issue by sunscreem** [statamic-rad-pack/shopify#264]
### Description

Morning @ryanmitchell 

I'm getting this undefined error in `ImportSingleProductJob.php`.

I think the issue is here - $qty doesn't exist:

https://github.com/sunscreem/shopify/blob/5fc35ddd8a7bad9fe43438d93f6de97c1848cd04/src/Jobs/ImportSingleProductJob.php#L461

### Steps to reproduce

N/A

### Environment

N/A

**Comment by ryanmitchell** [comment]
I've opened a PR with the (as yet untested) changes required: https://github.com/statamic-rad-pack/shopify/pull/265

**Comment by sunscreem** [comment]
I've pulled that in, and seems to working well @ryanmitchell thanks
