### ISSUE TITLE
Error on vendor:publish

### ISSUE THREAD

**Issue by malpaso** [statamic-rad-pack/shopify#266]
### Description

I am trying to publish the vendor assets as per https://statamic-shopify-docs.vercel.app/setup#publishable-assets and receiving the following error:
` php artisan vendor:publish --provider="StatamicRadPack\Shopify\ServiceProvider"

   ErrorException

  mkdir(): No such file or directory

  at vendor\shopify\shopify-api\src\Auth\FileSessionStorage.php:22
     18▕      */
     19▕     public function __construct(string $path = '/tmp/shopify_api_sessions')
     20▕     {
     21▕         if (!is_dir($path)) {
  ➜  22▕             mkdir($path);
     23▕         }
     24▕
     25▕         $this->path = $path;
     26▕     }

  1   vendor\shopify\shopify-api\src\Auth\FileSessionStorage.php:22

  2   vendor\statamic-rad-pack\shopify\src\ServiceProvider.php:149
      Shopify\Auth\FileSessionStorage::__construct("/tmp/php_sessions")`

### Steps to reproduce

On Windows:
1. Create a new blank Statamic site
2. Install the Rad Pack Shopify addon
3. Run the following from the command line: `php artisan vendor:publish --provider="StatamicRadPack\Shopify\ServiceProvider"`

### Environment

`php please support:details

   ErrorException

  mkdir(): No such file or directory

  at vendor\shopify\shopify-api\src\Auth\FileSessionStorage.php:22
     18▕      */
     19▕     public function __construct(string $path = '/tmp/shopify_api_sessions')
     20▕     {
     21▕         if (!is_dir($path)) {
  ➜  22▕             mkdir($path);
     23▕         }
     24▕
     25▕         $this->path = $path;
     26▕     }

  1   vendor\shopify\shopify-api\src\Auth\FileSessionStorage.php:22

  2   vendor\statamic-rad-pack\shopify\src\ServiceProvider.php:149
      Shopify\Auth\FileSessionStorage::__construct("/tmp/php_sessions")`

**Comment by ryanmitchell** [comment]
You need to specify a different session storage path in your config: 

https://github.com/statamic-rad-pack/shopify/blob/7fbd3b31e76bd6442cc8a04a1f8e7b3e3f552380/config/shopify.php#L128

You can use the `SHOPIFY_SESSION_STORAGE_PATH` .env value.
