### ISSUE TITLE
Import metafields as defined in Shopify

### ISSUE THREAD

**Issue by jackabox** [statamic-rad-pack/shopify#76]
I want to expand the add-on to account for meta fields in some way. 

Matching these up automatically I don't believe will work, but I'm keen to add support for this so you can extend as needed. 

Some predefined types should be made, such as:
- Text
- Image

Then you can extend as necessary with your own classes to map the importer.

**Comment by austriker27** [comment]
I'd love this as I plan on using meta fields for a few different things like 'retiring products'

**Comment by ryanmitchell** [comment]
What about just firing an event with the data array on product update/create, then devs can listen for that event and pick out the meta field data and do what we want with it? The other issue is how to get metafield data in the web hook payload - from my (brief) testing I cant get that data to be sent?

**Comment by jensolafkoch** [comment]
I'd like to see an implementation where you can opt in via config file shooify.php to either get the metafields (boolean) or not and then specify the ones you want (or just say 'all' maybe). 

Metafields which are not listed any more should be deleted in product entries.

*

What I do right now to get metafield content is to hook into the boot() function in AppServiceProvider to get all the metafields of any imported product via a MetafieldsController, which is a bit awkward:

```
        Queue::after(function (JobProcessed $event) {

            $payload = $event->job->payload();
            $soughtJob = "Jackabox\Shopify\Jobs\ImportSingleProductJob"; // Statamic-Addon: Shopify
            $jobDisplayName = Arr::get($payload, 'displayName');

            if(Str::endsWith($jobDisplayName, $soughtJob)) {

                $job = unserialize($payload['data']['command']);

                $productId = Arr::get($job->data, 'id');

                MetafieldsController::getMetafields($productId);

            }

        });

```

```
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Arr;
use PHPShopify\ShopifySDK;
use Statamic\Facades\Config;
use Statamic\Facades\Entry;

class MetafieldsController extends Controller
{

    public static function getMetafields($productId)
    {

        $shopify = new ShopifySDK();

        $product = Entry::query()
            ->where('collection', 'products')
            ->where('product_id', $productId)
            ->first();

        $metafieldResource = $shopify->Metafield();

        $fieldMappings = Config::get('shopify.field_mappings');

        $metafields = $metafieldResource->get([
            'limit' => config('shopify.api_limit'),
            "metafield" => ["owner_id" => $productId, "owner_resource" => "product"]
        ]);

        foreach($metafields as $metafield) {


            $fieldnameShopify = $metafield['key'];
            $fieldnameStatamic = Arr::get($fieldMappings, $fieldnameShopify);

            $product->{ $fieldnameStatamic } = $metafield['value'];

        }

        $product->save();

    }

}

```
