### ISSUE TITLE
Sub-Totals in rows don't get updated if amount is changed

### ISSUE THREAD

**Issue by delz-dev** [statamic-rad-pack/shopify#97]
<img width="965" alt="CleanShot 2021-11-02 at 14 16 51@2x" src="https://user-images.githubusercontent.com/54885840/139854222-3ac0044d-eaa1-43ce-9daf-a4e1e67976ae.png">

even in demo-shop it isn't working.

**Comment by localghost8000** [comment]
For what its worth, I just tested this and it seems to be working fine.

**Comment by delz-dev** [comment]
well its not working on the demo shop 🤷🏻‍♂️

**Comment by jackabox** [comment]
@delz-dev Can confirm that the subtotal in the last column doesn't update on the demo site.

**Comment by jensolafkoch** [comment]
This seems to be still open, which is something which may confuse/annoy visitors/buyers.

Has anyone a workaround?
